CREATE DATABASE KFC1
GO
USE KFC1

CREATE TABLE NHOMMONAN(
MANHOM INT PRIMARY KEY IDENTITY ,
TENNHOM NVARCHAR(50)
)

CREATE TABLE MONAN
(
 MAMONAN INT PRIMARY KEY IDENTITY,
 TENMONAN VARCHAR(50),
 MANHOM INT REFERENCES NHOMMONAN,
 HINHANH IMAGE,
 GIA INT 
 )

 CREATE TABLE KHACHHANG(
 USERNAME varchar(50),
 MATKHAU varchar(20),
 MAKH INT PRIMARY KEY IDENTITY,
 TENKH NVARCHAR(50),
 SDT INT
 )

 alter table Khachhang alter column sdt varchar(20)

 CREATE TABLE HOADON(
 MAHD INT PRIMARY KEY IDENTITY,
 MAKH INT REFERENCES KHACHHANG,
 NGAY DATE,
 TONGTIEN INT
 )

 CREATE TABLE CHITIETHOADON(
 MAHD INT REFERENCES HOADON,
 MAMONAN INT REFERENCES MONAN,
 SOLUONG INT
 )

CREATE TABLE SUKIEN(
MASK INT PRIMARY KEY IDENTITY,
TENSK NVARCHAR(50),
NGAYBATDAU DATE,
NGAYKETTHUC DATE,
MANHOM INT REFERENCES NHOMMONAN,
MOTA NVARCHAR(200)
)


CREATE TABLE CHITIETSK(
MASK INT REFERENCES SUKIEN,
MANHOM INT REFERENCES NHOMMONAN,
MUCGIAMGIA VARCHAR(10)
) 






